### ISSUE TITLE
test

### ISSUE THREAD

**Issue by johntom** [pixelmund/full-stack-svelte-kit-example#1]
I tried to use this eample and get the following
PS D:\devel\Svelte\svemix-example> npm run dev -- --open

> svemix-example@0.0.1 dev
> svelte-kit dev "--open"

> config.kit.target is no longer required, and should be removed
    at file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:874:10
    at file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:766:43
    at file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:752:18
    at validate_config (file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:936:9)
    at load_config (file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:913:20)
    at async file:///D:/devel/Svelte/svemix-example/node_modules/@sveltejs/kit/dist/cli.js:1013:19
PS D:\devel\Svelte\svemix-example> 
node 16.3.0
windows10

**Comment by pixelmund** [comment]
Hey the example wasn't updated in a while, i have done it now. Please note that i'm not really happy with the current state of the example, it would need some love but i don't have time for it atm.

**Comment by johntom** [comment]
Thanks, just want to view example. I will update my experience.
J
